# version: "3"
# services:
#   app:
#     build: .
#     volumes:
#       - ./:/go/src/golang_chat
#     ports:
#       - "8080:8080"

version: "3.7"
services:
  app:
    build: .
    volumes:
      - ./:/go/src/golang_chat
    ports:
      - "8080:8080"

